### ISSUE TITLE
docker:start failing on ubuntu 14

### ISSUE THREAD

**Issue by ntrvic** [alexec/docker-maven-plugin#56] opened 2015-05-14 16:30 UTC
Hi Alex,

Ran into an issue with the plugin on ubuntu:

adminuser@adminuser-VirtualBox:~/Documents/workfusion$ mvn docker:start -N -Pdocker-linux
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.freedomoss.crowdcontrol:workfusion-application:pom:7.2.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for com.alexecollins.docker:docker-maven-plugin is missing. @ line 137, column 33
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WorkFusion Application 7.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:2.8.4:start (default-cli) @ workfusion-application ---
12:27:37,547 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
12:27:37,547 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:27:37,547 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/adminuser/.m2/repository/com/alexecollins/docker/docker-maven-plugin/2.8.4/docker-maven-plugin-2.8.4.jar!/logback.xml]
12:27:37,592 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7f473ec7 - URL [jar:file:/home/adminuser/.m2/repository/com/alexecollins/docker/docker-maven-plugin/2.8.4/docker-maven-plugin-2.8.4.jar!/logback.xml] is not of type file
12:27:37,707 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
12:27:37,718 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.alexecollins.docker.util.MavenLogAppender]
12:27:37,718 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MAVEN]
12:27:37,734 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:18 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
12:27:37,735 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@7:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
12:27:37,735 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
12:27:37,735 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [MAVEN] to Logger[ROOT]
12:27:37,735 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:27:37,739 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1e6abc19 - Registering current configuration as safe fallback point

[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.024s
[INFO] Finished at: Thu May 14 12:27:38 EDT 2015
[INFO] Final Memory: 12M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:start (default-cli) on project workfusion-application: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Thanks,

Victor

**Comment by ntrvic** [comment] 2015-05-14 16:31
Someone got the same issue on windows but that was due to DOCKER_CERT_PATH missing.

**Comment by ntrvic** [comment] 2015-05-14 16:44
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:start (default-cli) on project workfusion-application: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.4:start (default-cli) on project workfusion-application: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:144)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:513)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:408)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:308)
    at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
    at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:12)
    at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
    at com.alexecollins.docker.mojo.AbstractDockerMojo.execute(AbstractDockerMojo.java:141)
    ... 21 more
Caused by: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:99)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:465)
    ... 35 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by alexec** [comment] 2015-05-14 19:25
Hi - can you try with version 2.8.6-SNAPSHOT please?

**Comment by ntrvic** [comment] 2015-05-14 21:42
adminuser@adminuser-VirtualBox:~/Documents/workfusion$ mvn docker:start -N -Pdocker-linux
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building WorkFusion Application 7.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:2.8.6-SNAPSHOT:start (default-cli) @ workfusion-application ---
17:41:07,791 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:41:07,792 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:41:07,792 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/adminuser/.m2/repository/com/alexecollins/docker/docker-maven-plugin/2.8.6-SNAPSHOT/docker-maven-plugin-2.8.6-SNAPSHOT.jar!/logback.xml]
17:41:07,830 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@1f36f64 - URL [jar:file:/home/adminuser/.m2/repository/com/alexecollins/docker/docker-maven-plugin/2.8.6-SNAPSHOT/docker-maven-plugin-2.8.6-SNAPSHOT.jar!/logback.xml] is not of type file
17:41:07,953 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:41:07,965 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.alexecollins.docker.util.MavenLogAppender]
17:41:07,965 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MAVEN]
17:41:07,995 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:18 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
17:41:07,995 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@7:22 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][pattern]]
17:41:07,996 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:41:07,996 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [MAVEN] to Logger[ROOT]
17:41:07,996 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:41:07,997 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@15160f3c - Registering current configuration as safe fallback point

[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request: https protocol is not supported
[INFO] Retrying request
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.289s
[INFO] Finished at: Thu May 14 17:41:09 EDT 2015
[INFO] Final Memory: 12M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.6-SNAPSHOT:start (default-cli) on project workfusion-application: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by bheku** [comment] 2015-05-18 09:58
Hi Alex,

I can report the same issue as @ntrvic on Ubuntu 14.04, with version 2.8.6-SNAPSHOT. Virtually the same stack trace, except I was trying to run:

mvn install -Prun-its

**Comment by alexec** [comment] 2015-05-18 11:07
Can I ask:

- Did this work for you before, and then stop working one day?
- Can you run `docker info` OK?
- Can you run `env|grep DOCKER` and attach the output?

**Comment by bheku** [comment] 2015-05-18 11:58
1) Never worked unfortunately. Only recently discovering docker so tried the example at 

http://www.alexecollins.com/docker-maven-plugin/

and that's the first time I saw the exception.


2) docker info:
Images: 45
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.59 GiB
Name: [redacted]
ID: H4OD:4JDG:CHGK:N4UN:YFXR:ZTWS:ZFBA:JWMG:XL4D:D4KN:NBJF:NL2M
WARNING: No swap limit support

env | grep DOCKER
DOCKER_CERT_PATH=

The last bit was me, read somewhere that having that environment variable unset may fix the problem. It didn't

**Comment by alexec** [comment] 2015-05-18 12:04
Try unsetting `DOCKER_CERT_PATH`? If not, you need to set the values as per here: https://github.com/docker-java/docker-java#system-environment

**Comment by bheku** [comment] 2015-05-19 09:23
Hi Alex, 

Thanks for your prompt response. I had a look at the link and it's muddling things for me somewhat... I'm really new to docker, so please bear with me. All I did is follow the installation instructions on the Docker site, and checked to see if everything was running ok, by going through their documentation.  

However, I can't completely reconcile everything in the link you posted. For example, I can't find any properties file for docker, amongst other things.

I did however update the docker defaults (/etc/default/docker) as follows:

DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"
DOCKER_CERT_PATH=
DOCKER_TLS_VERIFY=0

And set the DOCKER_URL environment variable:

export DOCKER_URL=http://localhost:2375

After which, the error disappeared :) 


But it's not all joy and happiness just yet. The project (drop-wizard-in-a-box) won't compile, it's having issues with annotations being used:

[ERROR] /home/bheku/git/docker/drop-wizard-in-a-box/src/main/java/com/example/helloworld/PeopleDAO.java:[9,42] error: generics are not supported in -source 1.3

If I'm not mistaken the above can easily be resolved by specifying the java source level. I will update as soon as I'm done.

**Comment by bheku** [comment] 2015-05-19 11:42
Looks like my joy was rather short-lived, getting this error now:

[INFO] Pinging http://localhost:8080/hello-world for pattern ".*"
[INFO] Logs (max last 10 lines) from container 38da58f602f7d8ad0ea55e1238f508bc45ecfc14efd34f076cbba89af97d735b: 
	STDERR: Caused by: java.net.ConnectException: Connection refused
	STDERR: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
	STDERR: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	STDERR: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	STDERR: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	STDERR: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	STDERR: 	at java.net.Socket.connect(Socket.java:579)
	STDERR: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)
	STDERR: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)
	STDERR: 	... 26 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:16.899s
[INFO] Finished at: Tue May 19 13:02:07 SAST 2015
[INFO] Final Memory: 43M/517M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "run-its" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.alexecollins.docker:docker-maven-plugin:2.8.6-SNAPSHOT:start (default) on project drop-wizard-in-a-box: timeout waiting for http://localhost:8080/hello-world for 60000 with pattern .* -> [Help 1]
[ERROR]

**Comment by alexec** [comment] 2015-05-19 12:01
Do `mvn docker:start` and then to `curl http://localhost:8080/hello-world`?

**Comment by bheku** [comment] 2015-05-19 12:04
Hangs at 

mvn docker:start

then times out.

**Comment by alexec** [comment] 2015-05-20 08:05
Are you on Mac or Linux?

**Comment by bheku** [comment] 2015-05-20 15:19
Sorry for the delayed response, busy day.

Ubuntu 14.04

**Comment by andyp1per** [comment] 2015-05-26 09:24
I have the same issue. The problem is that the plugin is assuming that docker has https access, but on Linux this is not true by default. It is true on platforms using boot2docker - which is why they work. If you specify <host>http://localhost:2375</host> the problem goes away on Linux, but on boot2docker platforms this is wrong and will fail. It would be nice to have a solution that is portable across buld platforms. I would expect not specifying <host/> to mean that the docekr defaults are used, but this is not currently true.

**Comment by bheku** [comment] 2015-05-26 10:49
Thanks @andyp1per. I only figured out about setting localhost after @alexec pointed out some default docker settings that need to be in place for the plugin to work on Ubuntu.

But still need to figure out what's causing it not to run, even after all the tweaking I did.

**Comment by alexec** [comment] 2015-05-26 12:25
Interesting. I'll look into this.

**Comment by alexec** [comment] 2015-05-26 19:57
I've updated the READMD.md with a comment about this. As the configuration comes from docker-java, I'm not sure I can force it to default to non-secure on Linux by default. That means this might be a WNF I'm afraid.

**Closed by alexec** 2015-05-26 19:57 UTC
Labels: bug

**Comment by bheku** [comment] 2015-05-27 08:14
Thanks for the feedback thus far.

**Comment by andyp1per** [comment] 2015-05-27 09:39
I was able to work around this by creating a Linux-only profile for the host setting. It's possible that my initial analysis is wrong in that it may be that SSL is enforced in later versions of docker.

**Comment by stalet** [comment] 2016-04-08 12:26
I am also getting this error running Ubuntu 14.04. Should the `<host>http://localhost:2375</host>` configuration be added as a properties in the pom.xml ?

**Comment by alexec** [comment] 2016-04-09 12:57
Hi @stalet  -- can you check our DOCKER_* environment variables are set and you can run `docker version` in the same terminal?
