### ISSUE TITLE
Goal "start" is rebuilding the image 

### ISSUE THREAD

**Issue by eemmiirr** [alexec/docker-maven-plugin#45] opened 2015-04-06 17:03 UTC
When "start" goal is run it's triggering the rebuild of the image even the image exists in the local images.

**Comment by alexec** [comment] 2015-04-07 00:23
Ah - does this occur when you do start twice in a row?

**Comment by eemmiirr** [comment] 2015-04-07 00:27
It occurs when i do just run mvn clean install with the following config. When i rerun it again it doesn't take the prebuild image it builds it again

<plugin>
                        <groupId>com.alexecollins.docker</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>2.4.0</version>
                        <configuration>
                            <host>http://localhost:2375</host>
                            <cache>true</cache>
                            <removeIntermediateImages>false</removeIntermediateImages>
                        </configuration>
                        <executions>
                            <execution>
                                <id>start</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

**Comment by alexec** [comment] 2015-04-07 00:29
Hmmm - any chance you can provide the source code?

**Comment by eemmiirr** [comment] 2015-04-07 00:33
The docker image i am trying to build?

**Comment by alexec** [comment] 2015-04-07 00:34
Basically, I don't know what the issue is, so I'd like to get more information to diagnose it. Perhaps the easiest thing would be to paste the command line output?

**Comment by eemmiirr** [comment] 2015-04-07 00:45
It seems like it builds first the image and its ok. It tags is as test/redis-cluster:3.0.0 but then when it get to the start goal it does:
```
[INFO] Docker version 1.5.0
[INFO] 3 * Sending client request on thread main
3 > GET http://localhost:2375/images/null%2Fuser-service_redis/json
3 > Accept: application/json

```

**Comment by alexec** [comment] 2015-04-08 20:02
*Should be* fixed in 2.4.1.

**Closed** 2015-04-09 18:49 UTC
